// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parlem.DAL;

#nullable disable

namespace Parlem.DAL.Migrations
{
    [DbContext(typeof(ParlemDBContext))]
    partial class ParlemDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parlem.DAL.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DocNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyName1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyName2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 555555,
                            CustomerId = "11111",
                            DocNum = "11223344E",
                            DocType = "nif",
                            Email = "it@parlem.com",
                            FamilyName1 = "Parlem",
                            FamilyName2 = "Parlem",
                            GivenName = "Enrique",
                            Phone = "668668668"
                        },
                        new
                        {
                            Id = 555556,
                            CustomerId = "11112",
                            DocNum = "22334455E",
                            DocType = "nif",
                            Email = "it2@parlem.com",
                            FamilyName1 = "Parlem",
                            FamilyName2 = "Parlem",
                            GivenName = "Test",
                            Phone = "600600600"
                        });
                });

            modelBuilder.Entity("Parlem.DAL.Entities.CustomerProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumeracioTerminal")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerProduct", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1111111,
                            CustomerId = "11111",
                            NumeracioTerminal = 933933933,
                            ProductName = "FIBRA 1000 ADAMO",
                            ProductTypeName = "ftth",
                            SoldAt = new DateTime(2019, 1, 9, 14, 26, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1111112,
                            CustomerId = "11111",
                            NumeracioTerminal = 944944944,
                            ProductName = "FIBRA 500 ADAMO",
                            ProductTypeName = "ftth",
                            SoldAt = new DateTime(2018, 1, 1, 10, 0, 20, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Parlem.DAL.Entities.CustomerProductEntity", b =>
                {
                    b.HasOne("Parlem.DAL.Entities.CustomerEntity", "Customer")
                        .WithMany("Products")
                        .HasForeignKey("CustomerId")
                        .HasPrincipalKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Parlem.DAL.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
